<a href="https://colab.research.google.com/github/renukadimi/Day1_ML/blob/main/Day1ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [2]:
# Numpy is for Mathematical operations

import numpy as np

a=[1,2,3,4,5]

arr1 = np.array(a)

b=[[1,2,3,4],[5,6,7,8]]

arr2 = np.array(b)

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [7]:
print(type(a),type(arr1),type(b),type(arr2))


<class 'list'> <class 'numpy.ndarray'> <class 'list'> <class 'numpy.ndarray'>


In [8]:
import sys

s=range(1000)

print("size of each element in the list in bytes",sys.getsizeof(s))

print("Complete list in bytes",sys.getsizeof(s)*len(s))


size of each element in the list in bytes 48
Complete list in bytes 48000


In [12]:
# we are checking comparing between numpy size and normal size of sys package
import numpy as np

s=np.arange(1000)

print("Size of each element in the list in byte",s.itemsize)
print("Complete list size in bytes",s.itemsize*s.size)




Size of each element in the list in byte 8
Complete list size in bytes 8000


In [20]:
#import time library and executing time taking by the system
import time

a=range(1000) #[0,....999]
b=range(1000) #[0,....999]

start =time.time()

ab = [(a*b) for a,b in zip(a,b)] #List Comprehension

# Creating a concised form of complete list and for loop or any other conditional statements

end = time.time()

print("Total time taken for system execution is :",end - start)


Total time taken for system execution is : 0.00019431114196777344


In [15]:
#Implementing the above segment in numpy
import numpy as np
import time

arr1=np.arange(1000)
arr2=np.arange(1000)

start=time.time()

arr_mul = arr1*arr2

end =time.time()

print("Total time taken for execution is ",end - start)

Total time taken for execution is  0.00024628639221191406


In [16]:
#converting list to array
list1 =[1,2,3,4]
arr = np.array(list1)
print(arr)

[1 2 3 4]


In [19]:
# list1 +1 is not possible,arr+1 is possible right shifting
list1=[1,2,3,4]
arr=np.array(list1)
print(list1)
print(arr)
print(arr+1)
print(list1+1)

[1, 2, 3, 4]
[1 2 3 4]
[2 3 4 5]


TypeError: ignored